# Generated by Django 2.0.3 on 2018-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='customer_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
