# Generated by Django 2.0.3 on 2018-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='calificiacion',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='servicio',
            name='calificacion_chofer',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='calificacion_cliente',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
