# Generated by Django 2.0.3 on 2018-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180816_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='calificacion_chofer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='calificacion_cliente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
