# Generated by Django 2.0.3 on 2018-08-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20180820_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoracredito',
            name='order_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
