# Generated by Django 2.0.3 on 2019-06-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_bitacoracredito_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monederochofer',
            name='estatus_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.EstatusPago'),
            preserve_default=False,
        ),
    ]
