# Generated by Django 2.0.3 on 2019-06-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_monederochofer_estatus_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='tarjeta',
            table='tarjeta',
        ),
    ]
