# Generated by Django 2.0.3 on 2019-06-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_administradorciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='admin_ciudad',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.DO_NOTHING, to='config.AdministradorCiudad'),
            preserve_default=False,
        ),
    ]
