# Generated by Django 2.0.3 on 2019-06-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_callcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigUsuariosCiudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_administradores', models.PositiveIntegerField(default=3)),
                ('ciudad', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Ciudad')),
            ],
            options={
                'db_table': 'config_usuarios_ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfigUsuariosSitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_administradores', models.PositiveIntegerField(default=3)),
                ('max_callcenter', models.PositiveIntegerField(default=12)),
                ('sitio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Sitio')),
            ],
            options={
                'db_table': 'config_usuarios_sitio',
                'managed': True,
            },
        ),
    ]
